// AUTO-GENERATED by @lovable.dev/mcp-js — do not edit. Regenerated by the Vite plugin.
// To take ownership, delete this banner line; the plugin then leaves the file alone.
// supabase function: mcp
// Bundled from src/lib/mcp/index.ts by @lovable.dev/mcp-js.
// src/lib/mcp/index.ts
import { auth, defineMcp } from "npm:@lovable.dev/mcp-js@0.26.1";

// src/lib/mcp/tools/list-tournaments.ts
import { defineTool } from "npm:@lovable.dev/mcp-js@0.26.1";
import { z } from "npm:zod@^3.25.76";

// src/lib/mcp/supabase.ts
import { createClient } from "npm:@supabase/supabase-js@^2.84.0";
function runtimeEnv(name) {
  const runtime = globalThis;
  return runtime.Deno?.env?.get?.(name) ?? runtime.process?.env?.[name];
}
function configuredEnv(names) {
  for (const name of names) {
    const value = runtimeEnv(name)?.trim();
    if (value) return value;
  }
  return void 0;
}
function supabaseProjectUrl() {
  const url = configuredEnv(["SUPABASE_URL", "VITE_SUPABASE_URL"]);
  if (!url) throw new Error("SUPABASE_URL (or VITE_SUPABASE_URL) is required");
  return url;
}
function supabasePublishableKey() {
  const direct = configuredEnv([
    "SUPABASE_PUBLISHABLE_KEY",
    "VITE_SUPABASE_PUBLISHABLE_KEY"
  ]);
  if (direct) return direct;
  const keyset = runtimeEnv("SUPABASE_PUBLISHABLE_KEYS");
  if (keyset) {
    try {
      const parsed = JSON.parse(keyset);
      if (parsed && typeof parsed === "object" && !Array.isArray(parsed)) {
        const keys = parsed;
        const key = [keys.default, ...Object.values(keys)].find((v) => typeof v === "string" && v.trim().startsWith("sb_publishable_"))?.trim();
        if (key) return key;
      }
    } catch {
    }
  }
  const legacy = configuredEnv(["SUPABASE_ANON_KEY", "VITE_SUPABASE_ANON_KEY"]);
  if (legacy) return legacy;
  throw new Error("SUPABASE_PUBLISHABLE_KEY, SUPABASE_PUBLISHABLE_KEYS, or SUPABASE_ANON_KEY is required");
}
function supabaseForUser(ctx) {
  const token = ctx.getToken();
  if (!token) throw new Error("supabaseForUser requires a verified OAuth token");
  return createClient(supabaseProjectUrl(), supabasePublishableKey(), {
    global: { headers: { Authorization: `Bearer ${token}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}
function notAuthenticated() {
  return {
    content: [{ type: "text", text: "Not authenticated. Connect this app with your account first." }],
    isError: true
  };
}

// src/lib/mcp/tools/list-tournaments.ts
var list_tournaments_default = defineTool({
  name: "list_tournaments",
  title: "List tournaments",
  description: "List waterski tournaments with their dates, location, disciplines and status (upcoming, live, finished).",
  inputSchema: {
    status: z.enum(["upcoming", "live", "finished"]).optional().describe("Filter by tournament status."),
    limit: z.number().int().min(1).max(50).default(20).describe("Maximum number of tournaments to return.")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ status, limit }, ctx) => {
    if (!ctx.isAuthenticated()) return notAuthenticated();
    const supabase = supabaseForUser(ctx);
    let query = supabase.from("tournaments").select("id, name, location, status, disciplines, start_date, end_date, start_datetime, end_datetime, settled_at").order("start_date", { ascending: false }).limit(limit ?? 20);
    if (status) query = query.eq("status", status);
    const { data, error } = await query;
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [{ type: "text", text: JSON.stringify(data ?? [], null, 2) }],
      structuredContent: { tournaments: data ?? [] }
    };
  }
});

// src/lib/mcp/tools/get-tournament-markets.ts
import { defineTool as defineTool2 } from "npm:@lovable.dev/mcp-js@0.26.1";
import { z as z2 } from "npm:zod@^3.25.76";
var get_tournament_markets_default = defineTool2({
  name: "get_tournament_markets",
  title: "Get tournament markets",
  description: "Get the published prediction markets for a tournament, including each selection (athlete) and its current multiplier.",
  inputSchema: {
    tournament_id: z2.string().uuid().describe("The tournament UUID from list_tournaments.")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ tournament_id }, ctx) => {
    if (!ctx.isAuthenticated()) return notAuthenticated();
    const supabase = supabaseForUser(ctx);
    const { data: markets, error } = await supabase.from("markets").select("id, name, market_type, discipline, category, is_published").eq("tournament_id", tournament_id).eq("is_published", true);
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    const ids = (markets ?? []).map((m) => m.id);
    let selections = [];
    if (ids.length > 0) {
      const { data: sel, error: selError } = await supabase.from("selections").select("id, market_id, description, decimal_odds, result, athletes(name, country)").in("market_id", ids);
      if (selError) return { content: [{ type: "text", text: selError.message }], isError: true };
      selections = sel ?? [];
    }
    const result = (markets ?? []).map((m) => ({
      ...m,
      selections: selections.filter((s) => s.market_id === m.id)
    }));
    return {
      content: [{ type: "text", text: JSON.stringify(result, null, 2) }],
      structuredContent: { markets: result }
    };
  }
});

// src/lib/mcp/tools/get-my-wallet.ts
import { defineTool as defineTool3 } from "npm:@lovable.dev/mcp-js@0.26.1";
var get_my_wallet_default = defineTool3({
  name: "get_my_wallet",
  title: "Get my token balance",
  description: "Get the signed-in user's token wallet balance (earned and purchased tokens).",
  inputSchema: {},
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async (_input, ctx) => {
    if (!ctx.isAuthenticated()) return notAuthenticated();
    const supabase = supabaseForUser(ctx);
    const { data, error } = await supabase.from("token_wallets").select("earned_tokens, purchased_tokens, updated_at").eq("user_id", ctx.getUserId()).maybeSingle();
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    if (!data) return { content: [{ type: "text", text: "No wallet found for this account." }] };
    const wallet = {
      earned_tokens: data.earned_tokens,
      purchased_tokens: data.purchased_tokens,
      total_tokens: (data.earned_tokens ?? 0) + (data.purchased_tokens ?? 0),
      updated_at: data.updated_at
    };
    return {
      content: [{ type: "text", text: JSON.stringify(wallet, null, 2) }],
      structuredContent: { wallet }
    };
  }
});

// src/lib/mcp/tools/list-my-predictions.ts
import { defineTool as defineTool4 } from "npm:@lovable.dev/mcp-js@0.26.1";
import { z as z3 } from "npm:zod@^3.25.76";
var list_my_predictions_default = defineTool4({
  name: "list_my_predictions",
  title: "List my predictions",
  description: "List the signed-in user's predictions with stake, potential payout, market type and settlement status.",
  inputSchema: {
    status: z3.enum(["PENDING", "WON", "LOST", "VOID"]).optional().describe("Filter by prediction status."),
    limit: z3.number().int().min(1).max(100).default(25).describe("Maximum number of predictions to return.")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ status, limit }, ctx) => {
    if (!ctx.isAuthenticated()) return notAuthenticated();
    const supabase = supabaseForUser(ctx);
    let query = supabase.from("predictions").select(
      "id, tournament_name, athlete_name, discipline, category, market_type, staked_tokens, potential_payout, payout_tokens, status, created_at, settled_at"
    ).eq("user_id", ctx.getUserId()).order("created_at", { ascending: false }).limit(limit ?? 25);
    if (status) query = query.eq("status", status);
    const { data, error } = await query;
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [{ type: "text", text: JSON.stringify(data ?? [], null, 2) }],
      structuredContent: { predictions: data ?? [] }
    };
  }
});

// src/lib/mcp/tools/get-leaderboard.ts
import { defineTool as defineTool5 } from "npm:@lovable.dev/mcp-js@0.26.1";
import { z as z4 } from "npm:zod@^3.25.76";
var get_leaderboard_default = defineTool5({
  name: "get_leaderboard",
  title: "Get leaderboard",
  description: "Get the top players on the season leaderboard, plus the signed-in user's own rank and net token P&L.",
  inputSchema: {
    limit: z4.number().int().min(1).max(50).default(10).describe("How many top players to return.")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ limit }, ctx) => {
    if (!ctx.isAuthenticated()) return notAuthenticated();
    const supabase = supabaseForUser(ctx);
    const [top, mine] = await Promise.all([
      supabase.rpc("get_leaderboard_top", { p_limit: limit ?? 10 }),
      supabase.rpc("get_user_leaderboard_position", { p_user_id: ctx.getUserId() })
    ]);
    if (top.error) return { content: [{ type: "text", text: top.error.message }], isError: true };
    const myPosition = Array.isArray(mine.data) ? mine.data[0] ?? null : mine.data ?? null;
    const payload = { top: top.data ?? [], my_position: myPosition };
    return {
      content: [{ type: "text", text: JSON.stringify(payload, null, 2) }],
      structuredContent: payload
    };
  }
});

// src/lib/mcp/index.ts
var projectRef = "mgcqkprehxtqjmfoqsro";
var mcp_default = defineMcp({
  name: "waterski-predictions",
  title: "Waterski Predictions",
  version: "0.1.0",
  instructions: "Tools for Waterski Predictions. Browse IWWF tournaments and their published prediction markets, and read the signed-in user's token wallet, predictions and leaderboard position. All tools are read-only and act as the connected user.",
  auth: auth.oauth.issuer({
    issuer: `https://${projectRef}.supabase.co/auth/v1`,
    acceptedAudiences: "authenticated"
  }),
  tools: [list_tournaments_default, get_tournament_markets_default, get_my_wallet_default, list_my_predictions_default, get_leaderboard_default]
});

// lovable-mcp-supabase-entry.ts
import { createSupabaseHandler } from "npm:@lovable.dev/mcp-js@0.26.1/stacks/supabase";
Deno.serve(createSupabaseHandler(mcp_default, { functionName: "mcp" }));
