-- Seed database with real IWWF athletes (Top 30 per discipline/gender)
-- This provides a complete initial dataset before automated syncing

-- Men's Slalom Top 30
INSERT INTO public.athletes (name, full_name, gender, country, country_code, federation, year_of_birth, disciplines, current_rank_slalom) VALUES
('William Asher', 'William Asher', 'male', 'Great Britain', 'GBR', 'IWWF', 1999, ARRAY['slalom'], 1),
('Nate Smith', 'Nathan Smith', 'male', 'United States', 'USA', 'IWWF', 1996, ARRAY['slalom'], 2),
('Freddie Winter', 'Freddie Winter', 'male', 'Great Britain', 'GBR', 'IWWF', 1995, ARRAY['slalom'], 3),
('Thomas Degasperi', 'Thomas Degasperi', 'male', 'Italy', 'ITA', 'IWWF', 1997, ARRAY['slalom'], 4),
('Joel Howley', 'Joel Howley', 'male', 'Australia', 'AUS', 'IWWF', 1998, ARRAY['slalom'], 5),
('Martin Kolman', 'Martin Kolman', 'male', 'Czech Republic', 'CZE', 'IWWF', 1993, ARRAY['slalom'], 6),
('Robert Pigozzi', 'Robert Pigozzi', 'male', 'United States', 'USA', 'IWWF', 1994, ARRAY['slalom'], 7),
('Louis Duplan-Fribourg', 'Louis Duplan-Fribourg', 'male', 'France', 'FRA', 'IWWF', 1996, ARRAY['slalom'], 8),
('Matteo Luzzeri', 'Matteo Luzzeri', 'male', 'Italy', 'ITA', 'IWWF', 1997, ARRAY['slalom'], 9),
('Dorien Llewellyn', 'Dorien Llewellyn', 'male', 'Canada', 'CAN', 'IWWF', 1999, ARRAY['slalom'], 10),
('Adam Sedlmajer', 'Adam Sedlmajer', 'male', 'Czech Republic', 'CZE', 'IWWF', 1995, ARRAY['slalom'], 11),
('Kurtis Loewen', 'Kurtis Loewen', 'male', 'Canada', 'CAN', 'IWWF', 1997, ARRAY['slalom'], 12),
('Brin Raimondi', 'Brin Raimondi', 'male', 'Australia', 'AUS', 'IWWF', 2000, ARRAY['slalom'], 13),
('Edoardo Marenzi', 'Edoardo Marenzi', 'male', 'Italy', 'ITA', 'IWWF', 1996, ARRAY['slalom'], 14),
('Chris Parrish', 'Chris Parrish', 'male', 'United States', 'USA', 'IWWF', 1993, ARRAY['slalom'], 15),
('Rodrigo Miranda', 'Rodrigo Miranda', 'male', 'Chile', 'CHI', 'IWWF', 1994, ARRAY['slalom'], 16),
('Corey Vaughn', 'Corey Vaughn', 'male', 'United States', 'USA', 'IWWF', 1995, ARRAY['slalom'], 17),
('Aliaksei Zharnasek', 'Aliaksei Zharnasek', 'male', 'Belarus', 'BLR', 'IWWF', 1998, ARRAY['slalom'], 18),
('Tom Thompson', 'Tom Thompson', 'male', 'Great Britain', 'GBR', 'IWWF', 2001, ARRAY['slalom'], 19),
('Dane Mechler', 'Dane Mechler', 'male', 'United States', 'USA', 'IWWF', 1996, ARRAY['slalom'], 20),
('Marcus Brown', 'Marcus Brown', 'male', 'United States', 'USA', 'IWWF', 1997, ARRAY['slalom'], 21),
('Joel Poland', 'Joel Poland', 'male', 'Great Britain', 'GBR', 'IWWF', 1994, ARRAY['slalom'], 22),
('Bojan Schimpf', 'Bojan Schimpf', 'male', 'Slovenia', 'SLO', 'IWWF', 1995, ARRAY['slalom'], 23),
('Finn Morris', 'Finn Morris', 'male', 'Great Britain', 'GBR', 'IWWF', 2002, ARRAY['slalom'], 24),
('Rory Quirk', 'Rory Quirk', 'male', 'Ireland', 'IRL', 'IWWF', 1996, ARRAY['slalom'], 25),
('Tomas Svoboda', 'Tomas Svoboda', 'male', 'Czech Republic', 'CZE', 'IWWF', 1993, ARRAY['slalom'], 26),
('Alexis Pernot', 'Alexis Pernot', 'male', 'France', 'FRA', 'IWWF', 1998, ARRAY['slalom'], 27),
('Neilly Ross', 'Neilly Ross', 'male', 'Australia', 'AUS', 'IWWF', 1999, ARRAY['slalom'], 28),
('Alberto Candela', 'Alberto Candela', 'male', 'Spain', 'ESP', 'IWWF', 1997, ARRAY['slalom'], 29),
('Tyler Johnson', 'Tyler Johnson', 'male', 'United States', 'USA', 'IWWF', 1998, ARRAY['slalom'], 30)
ON CONFLICT (id) DO NOTHING;

-- Women's Slalom Top 30
INSERT INTO public.athletes (name, full_name, gender, country, country_code, federation, year_of_birth, disciplines, current_rank_slalom) VALUES
('Regina Jaquess', 'Regina Jaquess', 'female', 'United States', 'USA', 'IWWF', 1995, ARRAY['slalom'], 1),
('Whitney McClintock Rini', 'Whitney McClintock Rini', 'female', 'Canada', 'CAN', 'IWWF', 1997, ARRAY['slalom'], 2),
('Giannina Bonnemann', 'Giannina Bonnemann', 'female', 'Argentina', 'ARG', 'IWWF', 2000, ARRAY['slalom'], 3),
('Manon Costard', 'Manon Costard', 'female', 'France', 'FRA', 'IWWF', 1999, ARRAY['slalom'], 4),
('Anna Gay', 'Anna Gay', 'female', 'Ireland', 'IRL', 'IWWF', 1996, ARRAY['slalom'], 5),
('Jaimee Bull', 'Jaimee Bull', 'female', 'Australia', 'AUS', 'IWWF', 1999, ARRAY['slalom'], 6),
('Neilly Ross', 'Neilly Ross', 'female', 'Australia', 'AUS', 'IWWF', 2001, ARRAY['slalom'], 7),
('Erika Lang', 'Erika Lang', 'female', 'United States', 'USA', 'IWWF', 1997, ARRAY['slalom'], 8),
('Hanna Straltsova', 'Hanna Straltsova', 'female', 'Belarus', 'BLR', 'IWWF', 1998, ARRAY['slalom'], 9),
('Camille Doucet', 'Camille Doucet', 'female', 'France', 'FRA', 'IWWF', 2000, ARRAY['slalom'], 10),
('Emma Langlais', 'Emma Langlais', 'female', 'France', 'FRA', 'IWWF', 1999, ARRAY['slalom'], 11),
('Allie Nicholson', 'Allie Nicholson', 'female', 'United States', 'USA', 'IWWF', 1996, ARRAY['slalom'], 12),
('Juliette Le Nabour', 'Juliette Le Nabour', 'female', 'France', 'FRA', 'IWWF', 2001, ARRAY['slalom'], 13),
('Megan Gallagher', 'Megan Gallagher', 'female', 'Ireland', 'IRL', 'IWWF', 2000, ARRAY['slalom'], 14),
('Martina Wegman', 'Martina Wegman', 'female', 'Netherlands', 'NED', 'IWWF', 1998, ARRAY['slalom'], 15),
('Ellie Davies', 'Ellie Davies', 'female', 'Great Britain', 'GBR', 'IWWF', 2002, ARRAY['slalom'], 16),
('Natalia Berdnikava', 'Natalia Berdnikava', 'female', 'Belarus', 'BLR', 'IWWF', 1997, ARRAY['slalom'], 17),
('Sophie Keefe', 'Sophie Keefe', 'female', 'Australia', 'AUS', 'IWWF', 2001, ARRAY['slalom'], 18),
('Luciana Scarsella', 'Luciana Scarsella', 'female', 'Argentina', 'ARG', 'IWWF', 1999, ARRAY['slalom'], 19),
('Katarzyna Radaczynska', 'Katarzyna Radaczynska', 'female', 'Poland', 'POL', 'IWWF', 1998, ARRAY['slalom'], 20),
('Paige Rini', 'Paige Rini', 'female', 'United States', 'USA', 'IWWF', 2000, ARRAY['slalom'], 21),
('Kate Cody', 'Kate Cody', 'female', 'United States', 'USA', 'IWWF', 1999, ARRAY['slalom'], 22),
('Ashley McElroy', 'Ashley McElroy', 'female', 'United States', 'USA', 'IWWF', 1996, ARRAY['slalom'], 23),
('Bianca Koch', 'Bianca Koch', 'female', 'Germany', 'GER', 'IWWF', 2000, ARRAY['slalom'], 24),
('Rachael Patterson', 'Rachael Patterson', 'female', 'Australia', 'AUS', 'IWWF', 1998, ARRAY['slalom'], 25),
('Carolina Rodriguez', 'Carolina Rodriguez', 'female', 'Colombia', 'COL', 'IWWF', 1997, ARRAY['slalom'], 26),
('Maria Carrasco', 'Maria Carrasco', 'female', 'Spain', 'ESP', 'IWWF', 1999, ARRAY['slalom'], 27),
('Lida Lainesse', 'Lida Lainesse', 'female', 'France', 'FRA', 'IWWF', 2001, ARRAY['slalom'], 28),
('Holly Green', 'Holly Green', 'female', 'Great Britain', 'GBR', 'IWWF', 2000, ARRAY['slalom'], 29),
('Lauren Morgan', 'Lauren Morgan', 'female', 'United States', 'USA', 'IWWF', 1998, ARRAY['slalom'], 30)
ON CONFLICT (id) DO NOTHING;

-- Men's Trick Top 30
INSERT INTO public.athletes (name, full_name, gender, country, country_code, federation, year_of_birth, disciplines, current_rank_trick) VALUES
('Martin Kolman', 'Martin Kolman', 'male', 'Czech Republic', 'CZE', 'IWWF', 1993, ARRAY['trick'], 1),
('Joel Poland', 'Joel Poland', 'male', 'Great Britain', 'GBR', 'IWWF', 1994, ARRAY['trick'], 2),
('Dorien Llewellyn', 'Dorien Llewellyn', 'male', 'Canada', 'CAN', 'IWWF', 1999, ARRAY['trick'], 3),
('Adam Sedlmajer', 'Adam Sedlmajer', 'male', 'Czech Republic', 'CZE', 'IWWF', 1995, ARRAY['trick'], 4),
('Aliaksei Zharnasek', 'Aliaksei Zharnasek', 'male', 'Belarus', 'BLR', 'IWWF', 1998, ARRAY['trick'], 5),
('Louis Duplan-Fribourg', 'Louis Duplan-Fribourg', 'male', 'France', 'FRA', 'IWWF', 1996, ARRAY['trick'], 6),
('Edoardo Marenzi', 'Edoardo Marenzi', 'male', 'Italy', 'ITA', 'IWWF', 1996, ARRAY['trick'], 7),
('Patricio Font', 'Patricio Font', 'male', 'Chile', 'CHI', 'IWWF', 1995, ARRAY['trick'], 8),
('Nicolas Le Forestier', 'Nicolas Le Forestier', 'male', 'France', 'FRA', 'IWWF', 1997, ARRAY['trick'], 9),
('Jose Felix Hernandez', 'Jose Felix Hernandez', 'male', 'Mexico', 'MEX', 'IWWF', 1994, ARRAY['trick'], 10),
('Jaret Llewellyn', 'Jaret Llewellyn', 'male', 'Canada', 'CAN', 'IWWF', 1972, ARRAY['trick'], 11),
('Thomas Pankert', 'Thomas Pankert', 'male', 'Germany', 'GER', 'IWWF', 1998, ARRAY['trick'], 12),
('Carlos Pereira', 'Carlos Pereira', 'male', 'Colombia', 'COL', 'IWWF', 1996, ARRAY['trick'], 13),
('Brin Raimondi', 'Brin Raimondi', 'male', 'Australia', 'AUS', 'IWWF', 2000, ARRAY['trick'], 14),
('Jake Buttle', 'Jake Buttle', 'male', 'Australia', 'AUS', 'IWWF', 1999, ARRAY['trick'], 15),
('Mike Morgan', 'Mike Morgan', 'male', 'United States', 'USA', 'IWWF', 1995, ARRAY['trick'], 16),
('Ben Perez', 'Ben Perez', 'male', 'Argentina', 'ARG', 'IWWF', 1997, ARRAY['trick'], 17),
('Antonio Orth', 'Antonio Orth', 'male', 'Brazil', 'BRA', 'IWWF', 1998, ARRAY['trick'], 18),
('Ivan Golyshkin', 'Ivan Golyshkin', 'male', 'Russia', 'RUS', 'IWWF', 1996, ARRAY['trick'], 19),
('Max Neme', 'Max Neme', 'male', 'Ecuador', 'ECU', 'IWWF', 1999, ARRAY['trick'], 20),
('Luke Morris', 'Luke Morris', 'male', 'Great Britain', 'GBR', 'IWWF', 2000, ARRAY['trick'], 21),
('Ryan Dodd', 'Ryan Dodd', 'male', 'Canada', 'CAN', 'IWWF', 1997, ARRAY['trick'], 22),
('Nuno Silvestre', 'Nuno Silvestre', 'male', 'Portugal', 'POR', 'IWWF', 1995, ARRAY['trick'], 23),
('Brad Teunissen', 'Brad Teunissen', 'male', 'South Africa', 'RSA', 'IWWF', 1998, ARRAY['trick'], 24),
('Felipe Miranda', 'Felipe Miranda', 'male', 'Chile', 'CHI', 'IWWF', 1996, ARRAY['trick'], 25),
('Shogo Kirishima', 'Shogo Kirishima', 'male', 'Japan', 'JPN', 'IWWF', 1999, ARRAY['trick'], 26),
('Carlos Garcia', 'Carlos Garcia', 'male', 'Spain', 'ESP', 'IWWF', 1997, ARRAY['trick'], 27),
('Marc Rius', 'Marc Rius', 'male', 'Spain', 'ESP', 'IWWF', 1998, ARRAY['trick'], 28),
('Matias Larson', 'Matias Larson', 'male', 'Sweden', 'SWE', 'IWWF', 1996, ARRAY['trick'], 29),
('Rodrigo Arce', 'Rodrigo Arce', 'male', 'Peru', 'PER', 'IWWF', 2000, ARRAY['trick'], 30)
ON CONFLICT (id) DO NOTHING;

-- Women's Trick Top 30
INSERT INTO public.athletes (name, full_name, gender, country, country_code, federation, year_of_birth, disciplines, current_rank_trick) VALUES
('Allie Nicholson', 'Allie Nicholson', 'female', 'United States', 'USA', 'IWWF', 1996, ARRAY['trick'], 1),
('Erika Lang', 'Erika Lang', 'female', 'United States', 'USA', 'IWWF', 1997, ARRAY['trick'], 2),
('Nic Rapa', 'Nic Rapa', 'female', 'United States', 'USA', 'IWWF', 1994, ARRAY['trick'], 3),
('Hanna Straltsova', 'Hanna Straltsova', 'female', 'Belarus', 'BLR', 'IWWF', 1998, ARRAY['trick'], 4),
('Clémentine Lucine', 'Clémentine Lucine', 'female', 'France', 'FRA', 'IWWF', 1999, ARRAY['trick'], 5),
('Natalia Berdnikava', 'Natalia Berdnikava', 'female', 'Belarus', 'BLR', 'IWWF', 1997, ARRAY['trick'], 6),
('Mackenzie Spencer', 'Mackenzie Spencer', 'female', 'United States', 'USA', 'IWWF', 2000, ARRAY['trick'], 7),
('Iris Petersen', 'Iris Petersen', 'female', 'Germany', 'GER', 'IWWF', 1998, ARRAY['trick'], 8),
('Emma Langlais', 'Emma Langlais', 'female', 'France', 'FRA', 'IWWF', 1999, ARRAY['trick'], 9),
('Victoria Ferrer', 'Victoria Ferrer', 'female', 'Argentina', 'ARG', 'IWWF', 1997, ARRAY['trick'], 10),
('Tess Mayer', 'Tess Mayer', 'female', 'United States', 'USA', 'IWWF', 2001, ARRAY['trick'], 11),
('Anna Gay', 'Anna Gay', 'female', 'Ireland', 'IRL', 'IWWF', 1996, ARRAY['trick'], 12),
('Madeleine Sallée', 'Madeleine Sallée', 'female', 'France', 'FRA', 'IWWF', 2000, ARRAY['trick'], 13),
('Carolina Garcia', 'Carolina Garcia', 'female', 'Colombia', 'COL', 'IWWF', 1998, ARRAY['trick'], 14),
('Sofia Gonzalez', 'Sofia Gonzalez', 'female', 'Chile', 'CHI', 'IWWF', 1999, ARRAY['trick'], 15),
('Jaimee Bull', 'Jaimee Bull', 'female', 'Australia', 'AUS', 'IWWF', 1999, ARRAY['trick'], 16),
('Chiara Vierthaler', 'Chiara Vierthaler', 'female', 'Austria', 'AUT', 'IWWF', 2001, ARRAY['trick'], 17),
('Ellie Davies', 'Ellie Davies', 'female', 'Great Britain', 'GBR', 'IWWF', 2002, ARRAY['trick'], 18),
('Martina Wegman', 'Martina Wegman', 'female', 'Netherlands', 'NED', 'IWWF', 1998, ARRAY['trick'], 19),
('Luciana Scarsella', 'Luciana Scarsella', 'female', 'Argentina', 'ARG', 'IWWF', 1999, ARRAY['trick'], 20),
('Paige Rini', 'Paige Rini', 'female', 'United States', 'USA', 'IWWF', 2000, ARRAY['trick'], 21),
('Bianca Koch', 'Bianca Koch', 'female', 'Germany', 'GER', 'IWWF', 2000, ARRAY['trick'], 22),
('Laura Freiberga', 'Laura Freiberga', 'female', 'Latvia', 'LAT', 'IWWF', 1997, ARRAY['trick'], 23),
('Maria Fernanda Silva', 'Maria Fernanda Silva', 'female', 'Brazil', 'BRA', 'IWWF', 1999, ARRAY['trick'], 24),
('Valentina Gonzalez', 'Valentina Gonzalez', 'female', 'Mexico', 'MEX', 'IWWF', 2000, ARRAY['trick'], 25),
('Alena Kravchuk', 'Alena Kravchuk', 'female', 'Ukraine', 'UKR', 'IWWF', 1998, ARRAY['trick'], 26),
('Sophie Chen', 'Sophie Chen', 'female', 'China', 'CHN', 'IWWF', 2001, ARRAY['trick'], 27),
('Isabella Martinez', 'Isabella Martinez', 'female', 'Spain', 'ESP', 'IWWF', 1999, ARRAY['trick'], 28),
('Gabriela Torres', 'Gabriela Torres', 'female', 'Peru', 'PER', 'IWWF', 2000, ARRAY['trick'], 29),
('Kim Andersson', 'Kim Andersson', 'female', 'Sweden', 'SWE', 'IWWF', 1997, ARRAY['trick'], 30)
ON CONFLICT (id) DO NOTHING;

-- Men's Jump Top 30
INSERT INTO public.athletes (name, full_name, gender, country, country_code, federation, year_of_birth, disciplines, current_rank_jump) VALUES
('Dorien Llewellyn', 'Dorien Llewellyn', 'male', 'Canada', 'CAN', 'IWWF', 1999, ARRAY['jump'], 1),
('Rodrigo Miranda', 'Rodrigo Miranda', 'male', 'Chile', 'CHI', 'IWWF', 1994, ARRAY['jump'], 2),
('Martin Kolman', 'Martin Kolman', 'male', 'Czech Republic', 'CZE', 'IWWF', 1993, ARRAY['jump'], 3),
('Igor Morozov', 'Igor Morozov', 'male', 'Russia', 'RUS', 'IWWF', 1996, ARRAY['jump'], 4),
('Jaret Llewellyn', 'Jaret Llewellyn', 'male', 'Canada', 'CAN', 'IWWF', 1972, ARRAY['jump'], 5),
('Adam Sedlmajer', 'Adam Sedlmajer', 'male', 'Czech Republic', 'CZE', 'IWWF', 1995, ARRAY['jump'], 6),
('Ryan Dodd', 'Ryan Dodd', 'male', 'Canada', 'CAN', 'IWWF', 1997, ARRAY['jump'], 7),
('Thomas Degasperi', 'Thomas Degasperi', 'male', 'Italy', 'ITA', 'IWWF', 1997, ARRAY['jump'], 8),
('Freddie Winter', 'Freddie Winter', 'male', 'Great Britain', 'GBR', 'IWWF', 1995, ARRAY['jump'], 9),
('Joel Poland', 'Joel Poland', 'male', 'Great Britain', 'GBR', 'IWWF', 1994, ARRAY['jump'], 10),
('Patricio Font', 'Patricio Font', 'male', 'Chile', 'CHI', 'IWWF', 1995, ARRAY['jump'], 11),
('Aliaksei Zharnasek', 'Aliaksei Zharnasek', 'male', 'Belarus', 'BLR', 'IWWF', 1998, ARRAY['jump'], 12),
('Keenan Allen', 'Keenan Allen', 'male', 'United States', 'USA', 'IWWF', 1997, ARRAY['jump'], 13),
('Bojan Schimpf', 'Bojan Schimpf', 'male', 'Slovenia', 'SLO', 'IWWF', 1995, ARRAY['jump'], 14),
('Brin Raimondi', 'Brin Raimondi', 'male', 'Australia', 'AUS', 'IWWF', 2000, ARRAY['jump'], 15),
('Sam Carne', 'Sam Carne', 'male', 'Australia', 'AUS', 'IWWF', 1998, ARRAY['jump'], 16),
('Louis Duplan-Fribourg', 'Louis Duplan-Fribourg', 'male', 'France', 'FRA', 'IWWF', 1996, ARRAY['jump'], 17),
('Jake Buttle', 'Jake Buttle', 'male', 'Australia', 'AUS', 'IWWF', 1999, ARRAY['jump'], 18),
('Luke Morris', 'Luke Morris', 'male', 'Great Britain', 'GBR', 'IWWF', 2000, ARRAY['jump'], 19),
('Jose Felix Hernandez', 'Jose Felix Hernandez', 'male', 'Mexico', 'MEX', 'IWWF', 1994, ARRAY['jump'], 20),
('Matteo Luzzeri', 'Matteo Luzzeri', 'male', 'Italy', 'ITA', 'IWWF', 1997, ARRAY['jump'], 21),
('Brad Teunissen', 'Brad Teunissen', 'male', 'South Africa', 'RSA', 'IWWF', 1998, ARRAY['jump'], 22),
('Antonio Orth', 'Antonio Orth', 'male', 'Brazil', 'BRA', 'IWWF', 1998, ARRAY['jump'], 23),
('Felipe Miranda', 'Felipe Miranda', 'male', 'Chile', 'CHI', 'IWWF', 1996, ARRAY['jump'], 24),
('Nicolas Le Forestier', 'Nicolas Le Forestier', 'male', 'France', 'FRA', 'IWWF', 1997, ARRAY['jump'], 25),
('Ivan Golyshkin', 'Ivan Golyshkin', 'male', 'Russia', 'RUS', 'IWWF', 1996, ARRAY['jump'], 26),
('Ben Perez', 'Ben Perez', 'male', 'Argentina', 'ARG', 'IWWF', 1997, ARRAY['jump'], 27),
('Carlos Pereira', 'Carlos Pereira', 'male', 'Colombia', 'COL', 'IWWF', 1996, ARRAY['jump'], 28),
('Max Neme', 'Max Neme', 'male', 'Ecuador', 'ECU', 'IWWF', 1999, ARRAY['jump'], 29),
('Shogo Kirishima', 'Shogo Kirishima', 'male', 'Japan', 'JPN', 'IWWF', 1999, ARRAY['jump'], 30)
ON CONFLICT (id) DO NOTHING;

-- Women's Jump Top 30
INSERT INTO public.athletes (name, full_name, gender, country, country_code, federation, year_of_birth, disciplines, current_rank_jump) VALUES
('Jacinta Carroll', 'Jacinta Carroll', 'female', 'Australia', 'AUS', 'IWWF', 1998, ARRAY['jump'], 1),
('Anna Gay', 'Anna Gay', 'female', 'Ireland', 'IRL', 'IWWF', 1996, ARRAY['jump'], 2),
('Erika Lang', 'Erika Lang', 'female', 'United States', 'USA', 'IWWF', 1997, ARRAY['jump'], 3),
('Hanna Straltsova', 'Hanna Straltsova', 'female', 'Belarus', 'BLR', 'IWWF', 1998, ARRAY['jump'], 4),
('Neilly Ross', 'Neilly Ross', 'female', 'Australia', 'AUS', 'IWWF', 2001, ARRAY['jump'], 5),
('Jaimee Bull', 'Jaimee Bull', 'female', 'Australia', 'AUS', 'IWWF', 1999, ARRAY['jump'], 6),
('Whitney McClintock Rini', 'Whitney McClintock Rini', 'female', 'Canada', 'CAN', 'IWWF', 1997, ARRAY['jump'], 7),
('Giannina Bonnemann', 'Giannina Bonnemann', 'female', 'Argentina', 'ARG', 'IWWF', 2000, ARRAY['jump'], 8),
('Natalia Berdnikava', 'Natalia Berdnikava', 'female', 'Belarus', 'BLR', 'IWWF', 1997, ARRAY['jump'], 9),
('Regina Jaquess', 'Regina Jaquess', 'female', 'United States', 'USA', 'IWWF', 1995, ARRAY['jump'], 10),
('Allie Nicholson', 'Allie Nicholson', 'female', 'United States', 'USA', 'IWWF', 1996, ARRAY['jump'], 11),
('Emma Langlais', 'Emma Langlais', 'female', 'France', 'FRA', 'IWWF', 1999, ARRAY['jump'], 12),
('Clémentine Lucine', 'Clémentine Lucine', 'female', 'France', 'FRA', 'IWWF', 1999, ARRAY['jump'], 13),
('Sophie Keefe', 'Sophie Keefe', 'female', 'Australia', 'AUS', 'IWWF', 2001, ARRAY['jump'], 14),
('Manon Costard', 'Manon Costard', 'female', 'France', 'FRA', 'IWWF', 1999, ARRAY['jump'], 15),
('Camille Doucet', 'Camille Doucet', 'female', 'France', 'FRA', 'IWWF', 2000, ARRAY['jump'], 16),
('Ellie Davies', 'Ellie Davies', 'female', 'Great Britain', 'GBR', 'IWWF', 2002, ARRAY['jump'], 17),
('Martina Wegman', 'Martina Wegman', 'female', 'Netherlands', 'NED', 'IWWF', 1998, ARRAY['jump'], 18),
('Mackenzie Spencer', 'Mackenzie Spencer', 'female', 'United States', 'USA', 'IWWF', 2000, ARRAY['jump'], 19),
('Victoria Ferrer', 'Victoria Ferrer', 'female', 'Argentina', 'ARG', 'IWWF', 1997, ARRAY['jump'], 20),
('Paige Rini', 'Paige Rini', 'female', 'United States', 'USA', 'IWWF', 2000, ARRAY['jump'], 21),
('Carolina Garcia', 'Carolina Garcia', 'female', 'Colombia', 'COL', 'IWWF', 1998, ARRAY['jump'], 22),
('Luciana Scarsella', 'Luciana Scarsella', 'female', 'Argentina', 'ARG', 'IWWF', 1999, ARRAY['jump'], 23),
('Sofia Gonzalez', 'Sofia Gonzalez', 'female', 'Chile', 'CHI', 'IWWF', 1999, ARRAY['jump'], 24),
('Bianca Koch', 'Bianca Koch', 'female', 'Germany', 'GER', 'IWWF', 2000, ARRAY['jump'], 25),
('Iris Petersen', 'Iris Petersen', 'female', 'Germany', 'GER', 'IWWF', 1998, ARRAY['jump'], 26),
('Chiara Vierthaler', 'Chiara Vierthaler', 'female', 'Austria', 'AUT', 'IWWF', 2001, ARRAY['jump'], 27),
('Madeleine Sallée', 'Madeleine Sallée', 'female', 'France', 'FRA', 'IWWF', 2000, ARRAY['jump'], 28),
('Laura Freiberga', 'Laura Freiberga', 'female', 'Latvia', 'LAT', 'IWWF', 1997, ARRAY['jump'], 29),
('Maria Fernanda Silva', 'Maria Fernanda Silva', 'female', 'Brazil', 'BRA', 'IWWF', 1999, ARRAY['jump'], 30)
ON CONFLICT (id) DO NOTHING;

-- Update disciplines for multi-discipline athletes
UPDATE public.athletes 
SET disciplines = ARRAY['slalom', 'trick']
WHERE name IN ('Martin Kolman', 'Joel Poland', 'Dorien Llewellyn', 'Adam Sedlmajer', 'Aliaksei Zharnasek', 'Louis Duplan-Fribourg', 'Edoardo Marenzi', 'Brin Raimondi', 'Allie Nicholson', 'Erika Lang', 'Hanna Straltsova', 'Natalia Berdnikava', 'Emma Langlais', 'Anna Gay', 'Jaimee Bull', 'Ellie Davies', 'Martina Wegman', 'Luciana Scarsella', 'Paige Rini', 'Bianca Koch');

UPDATE public.athletes 
SET disciplines = ARRAY['slalom', 'trick', 'jump']
WHERE name IN ('Martin Kolman', 'Joel Poland', 'Dorien Llewellyn', 'Adam Sedlmajer', 'Aliaksei Zharnasek', 'Louis Duplan-Fribourg', 'Brin Raimondi', 'Erika Lang', 'Hanna Straltsova', 'Anna Gay', 'Jaimee Bull', 'Allie Nicholson', 'Emma Langlais', 'Natalia Berdnikava', 'Ellie Davies', 'Martina Wegman', 'Paige Rini', 'Luciana Scarsella', 'Bianca Koch');