-- Add comprehensive help articles for complete coverage

-- Contests & Rules: Additional articles
INSERT INTO help_articles (section, title, body, sort_order, is_active) VALUES
('Contests & Rules', 'How do odds work?', E'Odds show the potential payout for a winning entry.\n\n**Decimal Odds Explained:**\n- Odds of 2.50 mean you win 2.5x your stake\n- A 1,000 token bet at 2.50 odds = 2,500 tokens if you win\n\n**Why Odds Change:**\n- Odds are based on athlete performance ratings\n- Heavy betting on one athlete may shorten their odds\n- Odds are locked when you place your entry\n\n**American Odds (for reference):**\n- +150 means win $150 on a $100 bet\n- -150 means bet $150 to win $100\n- We display decimal odds by default\n\nYour potential payout is always shown before you confirm.', 6, true),

('Contests & Rules', 'What is a parlay?', E'A parlay combines multiple picks into one entry for higher potential payouts.\n\n**How Parlays Work:**\n1. Select 2 or more athletes across different events\n2. The odds multiply together\n3. ALL picks must win for you to win\n\n**Example:**\n- Pick 1: Athlete A at 2.0 odds\n- Pick 2: Athlete B at 1.8 odds\n- Combined odds: 2.0 × 1.8 = 3.6 odds\n- 1,000 tokens × 3.6 = 3,600 potential payout\n\n**Risk vs Reward:**\n❌ If ANY pick loses, you lose the entire stake\n✅ If ALL picks win, you win at multiplied odds\n\nParlays are high-risk, high-reward. Only bet what you can afford to lose!', 7, true),

('Contests & Rules', 'Fantasy contests explained', E'Fantasy contests let you build a dream team of athletes.\n\n**How It Works:**\n1. Enter a fantasy pot by paying the entry fee\n2. Build a team within the salary cap ($50,000)\n3. Athletes earn points based on their performance\n4. Highest-scoring teams win prizes\n\n**Scoring:**\n- Placement points (1st = 100, 2nd = 80, etc.)\n- Score bonuses for exceptional performances\n- Discipline-specific scoring rules\n\n**Prize Pools:**\n- Entry fees fund the prize pool\n- Top finishers split the pool\n- Larger pools = larger prizes\n\nCheck each contest for specific rules and prize structures.', 8, true);

-- Tokens & Limits: Additional articles  
INSERT INTO help_articles (section, title, body, sort_order, is_active) VALUES
('Tokens & Limits', 'Token security and safety', E'Your tokens are safe with us.\n\n**Important Information:**\n- Tokens are for entertainment purposes only\n- Tokens have NO cash value and cannot be withdrawn as cash\n- Earned tokens can be redeemed for rewards (gear, lessons, etc.)\n\n**Responsible Play:**\n- Set personal limits on spending\n- Never stake more than you can afford\n- Take breaks if you''re not enjoying it\n\n**Security:**\n- Your account is protected by secure authentication\n- Transaction history is always available\n- All activity is logged for your protection\n\nQuestions? Contact support at any time.', 6, true),

('Tokens & Limits', 'What happens to my tokens if I''m inactive?', E'Good news - your tokens don''t expire!\n\n**Token Persistence:**\n- Tokens remain in your account indefinitely\n- No expiration date on purchased or earned tokens\n- Your balance is always waiting for you\n\n**Account Status:**\n- Inactive accounts are not deleted\n- You can return and continue playing anytime\n- Your prediction history is preserved\n\n**Security Note:**\n- For security, we recommend logging in periodically\n- Keep your email address up to date\n- Contact support if you have access issues after extended absence', 7, true);

-- NEW SECTION: Account & Profile
INSERT INTO help_articles (section, title, body, sort_order, is_active) VALUES
('Account & Profile', 'How to create an account', E'Creating an account takes just a minute.\n\n**Steps:**\n1. Tap "Sign Up" on the login screen\n2. Enter your email address\n3. Create a secure password (min 6 characters)\n4. Verify your email if required\n5. Start exploring!\n\n**Password Tips:**\n- Use a unique password\n- Combine letters, numbers, and symbols\n- Don''t share your password with anyone\n\n**After Signup:**\n- Browse tournaments immediately\n- Get 10,000 bonus tokens as a new user!\n- Set up your profile in the Profile tab', 1, true),

('Account & Profile', 'How to reset your password', E'Forgot your password? No problem!\n\n**Reset Steps:**\n1. Go to the login screen\n2. Tap "Forgot Password?"\n3. Enter your email address\n4. Check your inbox for the reset link\n5. Click the link and set a new password\n\n**Tips:**\n- Check spam/junk folder if you don''t see the email\n- Links expire after a short time\n- Contact support if you still can''t access your account\n\nOnce reset, you can log in with your new password immediately.', 2, true),

('Account & Profile', 'How to view your betting history', E'Track all your entries in one place.\n\n**Finding Your Bets:**\n1. Tap the "My Bets" tab or go to Profile\n2. View all pending and settled entries\n3. Filter by status, date, or tournament\n\n**Entry Statuses:**\n- **PENDING:** Waiting for results\n- **WON:** You won! Tokens credited\n- **LOST:** Better luck next time\n- **VOID:** Entry refunded (athlete withdrawal, etc.)\n\n**Details Shown:**\n- Athlete and tournament name\n- Stake and potential payout\n- Odds at time of entry\n- Result and actual payout', 3, true),

('Account & Profile', 'How to manage your profile', E'Customize your WaterskiPredictor experience.\n\n**Profile Settings:**\n- Go to the Profile tab\n- View your username and email\n- Check your lifetime stats\n\n**What You Can Update:**\n- Display name / username\n- Email preferences\n- Notification settings\n\n**Account Security:**\n- Update your password anytime\n- Review login activity\n- Contact support for account changes\n\n**Stats Tracked:**\n- Total predictions made\n- Win rate percentage\n- Lifetime winnings', 4, true);

-- Troubleshooting: Additional articles
INSERT INTO help_articles (section, title, body, sort_order, is_active) VALUES
('Troubleshooting', 'My winnings weren''t credited', E'Winnings not showing? Here''s what to check:\n\n**1. Check Entry Status:**\n- Go to My Bets and find the entry\n- If still "PENDING," results aren''t finalized yet\n\n**2. Check Tournament Status:**\n- Results take 24-48 hours after event ends\n- Look for "Settled" or "Finalized" status\n\n**3. Check Your Wallet:**\n- Winnings go to your Earned Tokens balance\n- Check the Transactions page for credit history\n\n**Still Missing?**\n- Note the entry ID\n- Check the exact payout amount expected\n- Contact support with these details\n\nWe investigate all missing payout reports promptly.', 6, true),

('Troubleshooting', 'Payment processing issues', E'Having trouble purchasing tokens?\n\n**Card Declined:**\n- Verify card details are correct\n- Check available balance\n- Try a different card\n- Contact your bank if blocks persist\n\n**Pending Charges:**\n- Some charges show as "pending" for 24-48 hours\n- Pending charges that fail will be reversed\n- Don''t attempt multiple purchases if one is pending\n\n**Refunds:**\n- Refunds process within 5-10 business days\n- Check with your bank for exact timing\n\n**Still Having Issues?**\nContact support with:\n- Date and time of attempt\n- Last 4 digits of card used\n- Any error message shown', 7, true);